# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-07-28 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xray_age', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(blank=True, max_length=6)),
                ('weight', models.IntegerField()),
                ('image', models.ImageField(upload_to=b'')),
                ('age', models.IntegerField()),
            ],
        ),
    ]
