# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-07-29 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xray_age', '0002_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='image',
            field=models.ImageField(upload_to=b'/'),
        ),
    ]
