# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-07-30 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xray_age', '0003_auto_20180729_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='image',
            field=models.ImageField(upload_to=b'uploads/'),
        ),
    ]
